### ISSUE TITLE
disassembler view doesn't reflect function names

### ISSUE THREAD

**Issue by deepgray** [eteran/edb-debugger#535] opened 2017-01-21 22:36 UTC
using gdb, I can perform a disassemble and see the functions calls for each call with the associated name.

using edu, I see what looks like disassembled code, but there is no function call name--just the address.

**Comment by AaronOpfer** [comment] 2017-01-21 22:46
You should be able to see symbol names when they exist. Have you configured
a symbol path? What version of edb are you using? Can you reproduce this
with an example trivial application ("Hello World") you have compiled
yourself?

**Comment by eteran** [comment] 2017-01-26 14:32
@deepgray, Is the binary stripped? If so, edb won't be able to come up with many names. Please paste the output of the following two commands:

    nm <your_binary>
    nm -D <your_binary>

which will list both the normal symbols and the dynamic ones. If the function names you are looking for are not in those lists, and you don't have debugging symbols installed on your system for the binary (typically `/usr/lib/debug/path/to/<your_binary>.debug`), then edb won't be able to do much about that.

**Comment by eteran** [comment] 2017-02-11 19:26
@deepgray I am going to close this (for now) since there hasn't been any follow up and we are able to reproduce it locally with the information we have. Please feel free to reopen if you feel that this issue persists.

**Closed by eteran** 2017-02-11 19:26 UTC

**Comment by deepgray** [comment] 2017-02-23 00:15
sorry...off line for a while...a thing called vacation ;-)

i'll add the info.

**Comment by deepgray** [comment] 2017-02-23 00:36
[babypwn.zip](https://github.com/eteran/edb-debugger/files/795209/babypwn.zip)

attached are the files plus the binary. if you look at the objdump, it shows the function names (example is at address x080487cf...objdump shows the functon send() where as edb jsut shows an address.

this is running on kali 2 rolling i386 and has been brought up to date with apt-get upgrade and dist-upgrade.

the app indicated that there a more recent version but it's not in the repository.
