### ISSUE TITLE
Using python to create input.

### ISSUE THREAD

**Issue by orenbenya1** [eteran/edb-debugger#742] opened 2020-02-08 15:22 UTC
Hey, I am now trying to solve "unlink" challenge from pwnable, and while I debugged the program I got to a problem that I couldn't solve. If you look at the writeup here: https://raz0r.name/writeups/writeup-pwnable-kr-unlink/ you will see that the solver used:

"  r <<< `python -c 'from struct import pack; print(pack("<I", 0x80484eb) + "A" * 20 + pack("<I", 0xffffd2b4 - 4) + pack("<I", 0x804b578 + 4))'`"

in pwndbg in order to run the program and when it asks for input, use a python script to generate one according to the challenge. is there any way to do the same in edb? for example when we reach a "get" command, to create a special input using python, even better if we can to create the script according to the output we will get from the debugger. It would be awesome if we had a python scripting option in edb like that there is in x64dbg :)

thank you.

**Comment by eteran** [comment] 2020-02-08 20:42
Yea, this hits on two separate things that I'd like to add to edb.

1. would be the ability to specify stdin for the process (issue #627 )
2. Python scripting in general (issue #507 )

I hope to have these features eventually. But it's not always easy to find the time. They'll get in there eventually though!

Closing this, not because it isn't valid, but because it is technically a duplicate of sorts.

**Closed by eteran** 2020-02-08 20:42 UTC
