### ISSUE TITLE
Feature: Persistent Breakpoints (in base at least)

### ISSUE THREAD

**Issue by ttufts** [eteran/edb-debugger#684] opened 2018-12-06 03:36 UTC
I realize ASLR gets in the way of persistent breakpoints, but it would be excellent to have them in the base image at least.

**Comment by eteran** [comment] 2018-12-06 06:49
Duplicate of issue #358

**Comment by eteran** [comment] 2018-12-06 06:49
I do like the idea of "at least" supporting them in the base image. That in itself should make things much simpler.

**Closed by eteran** 2018-12-06 06:49 UTC
