### ISSUE TITLE
Feature: pipes/sockets for stdin/stdout/stderr for started process 

### ISSUE THREAD

**Issue by ttufts** [eteran/edb-debugger#686] opened 2018-12-06 03:47 UTC
Running a command line process and scripting input/output to it is easy with pwntools and other utilities... but then I need to attach to the running process with edb rather than running the executable from within edb. This can cause problems connecting immediately at start. 

Provide an api for connecting to input/output tubes for a process that's been run from inside edb.

**Comment by eteran** [comment] 2018-12-06 06:54
For now, a preliminary plan is to offer **something** like this:

    ./edb --io /path/to/unix/socket --run <program>

The idea is that the user can read/write arbitrary data to that local socket, and hopefully, that will allow them to easily connect the running binary to other processes which would produce its input or consume its output.

I think to think about this a bit further though.

**Comment by eteran** [comment] 2018-12-06 06:58
This is effectively a dupe of issue #627, so closing this one. I like the idea and I think it's useful particularly in a Unix debugger. It's just hard to come up with a reasonable workflow that makes sense in a general case.

**Closed by eteran** 2018-12-06 06:58 UTC

**Comment by eteran** [comment] 2020-03-06 21:39
Implemented!
