### ISSUE TITLE
Can not load DebuggerCore plugin on fedora 23 x86-64 w/ 3rd Party Qt 5.6

### ISSUE THREAD

**Issue by kuh3h3** [eteran/edb-debugger#361] opened 2016-04-10 03:25 UTC
just normal install. but edb cant find core plugin.
 cmake  -DCMAKE_INSTALL_PREFIX=/usr ..

in preference, Directory, there is /usr/lib64/edb, and there is some plugins in PLugin options.
but when run , always same error occured and exited.

**Comment by kuh3h3** [comment] 2016-04-10 04:04
Mabe cmake is  culprit. so tried to clean-rebuild with qmake.
qmake-qt5 -makefile DEFAULT_PLUGIN_PATH="/usr/lib64/edb" PREFIX=/usr

run ok , but this error occurred.
although error message,  run ok.

"Failed to setup program arguments and working directory entries for file open dialog, please report and be sure to tell your Qt version"
Segfault (core dumped)

**Comment by eteran** [comment] 2016-04-11 20:17
interesting, I will fire up a FC23 VM and see if I can get to the bottom of it

**Comment by eteran** [comment] 2016-04-11 21:01
OK, I have just run the cmake build steps on a fresh FC23 64 bit VM, and unfortunately, I cannot replicate this issue. Have any of the steps you run differed significantly from the (newly updated) wiki?

https://github.com/eteran/edb-debugger/wiki/Compiling-(Fedora)

Some things to try:

1. do a fresh checkout from git master, we've been fairly active this past year, so pleaser make sure you're trying the latest :-)
2. double check that in the plugin options, the plugins directory points to where all of the plugin .so files were installed. `/usr/lib64/edb` does seem right though.
3. try a **completely** clean install.
        rm -rf /usr/lib64/edb
        rm /usr/bin/edb
        rm -rf ~/.config/codef00.com
        # then do a fresh clone/build/install and see if that helps.

Let me know if this issue persists or if you have any other information that can help me reproduce this issue.

**Comment by kuh3h3** [comment] 2016-04-13 10:08
yes.did all you said. but same result(can`t find core plugin,and exit)  with cmake.
there is no special diferrent steps from  wiki. but i have fedora 23 x86-64 , qt5 5.6.
and SPECIFIED PREFIX.
Full rebuild log attached.

for the time being i will 
[edb-build.txt](https://github.com/eteran/edb-debugger/files/216809/edb-build.txt)
safe qmake-qt5 method.

**Comment by kuh3h3** [comment] 2016-04-13 10:42
i said "safe qmake-qt5 method" but Not  perfect safe. 
when exit, always segfaults.

**Comment by eteran** [comment] 2016-04-13 11:22
Interesting:

As a side note, you can work around that crash on close by going into the preferences and then the plugins section and finally disabling the "CheckVersion" plugin's check on startup feature. I will add an issue for that too.

**Comment by eteran** [comment] 2016-04-14 14:06
So one thing I've noticed is that the packages to satisfy  qt-devel on FC23 are version 4.8.7 on my stock install. Can you try cmake + Qt4 and let me know if it works?

    cmake -DQT_VERSION=Qt4 -DCMAKE_INSTALL_PREFIX=/usr ..

I will try with Qt5 packages and see if I can reproduce your issue.

**Comment by eteran** [comment] 2016-04-14 14:31
OK, confirmed to work with stock Qt5 on FC23, you say you are using Qt version 5.6. What is the source for that? `dnf install qt5-qtbase-devel` gives me 5.5.1.

**Comment by kuh3h3** [comment] 2016-04-14 15:30
https://copr.fedorainfracloud.org/coprs/g/kdesig/Qt5/

you can install it like this.

sudo dnf copr enable @kdesig/Qt5
sudo dnf update

**Comment by eteran** [comment] 2016-04-14 15:40
Great, will be testing this afternoon. As a side note, I've noticed that Fedora now has official capstone-devel packages, so going forward it is preferable to use those over compiled from source :-)

**Comment by kuh3h3** [comment] 2016-04-14 15:50
In qt4 build, all ok .
build, run .No problems. 
i`ll test capstone official package.

**Comment by eteran** [comment] 2016-04-14 17:11
OK, problem replicated with Qt 5.6 sources from kdesig/Qt5.

I can say that it does not appear to happen using the official Qt5 libs, so this may be an issue with the either Qt 5.6 in general or perhaps the kdesig packages specifically. I will investigate.

**Comment by eteran** [comment] 2016-04-14 17:48
This is VERY weird. For reference, here's what I've found so far:

1. The plugin is failing to load with a "Plugin verification data mismatch" error.
2. Here's the weird part. A little googling traces this error typically to a missing `Q_PLUGIN_METADATA` entry in the plugin... But we have one. It is wrapped in `#f QT_VERSION >= 0x050000` (which is true, so it happens). If I remove the `#if`, then it works!

so why do these two pieces of code produce different binaries:

    #if QT_VERSION >= 0x050000
        Q_PLUGIN_METADATA(IID "edb.IDebugger/1.0")
    #endif

and 

        Q_PLUGIN_METADATA(IID "edb.IDebugger/1.0")

If the `QT_VERSION` macro is `0x050600`? Simply removing the #if, which succeeds makes it load! so weird.

**Comment by eteran** [comment] 2016-04-14 17:56
Yea, I may have to chalk this one up to either a compiler bug or a Qt 5.6 bug. The only different between the two files after the preprocessor runs in white-space, yet they produce different binaries :-/. I don't know what to do about that, but I'll look a little more.

**Comment by eteran** [comment] 2016-04-14 18:13
That being said, the fact that using `qmake-qt5` results in a properly working plugin means that it's gotta be some difference in how it is being built. This is very strange indeed.

**Comment by 10110111** [comment] 2016-04-14 18:37
Just today I've heard from a colleague that in qt 5.6 something related to plugin API had changed. This might be the reason for the problems.

**Comment by eteran** [comment] 2016-12-08 22:00
I am going to file this under "issue with 3rd party build of Qt5", since it only is able to be replicated under those circumstances.

Closing for now.

If this issue ever comes up with an "official" build of Qt, then please feel free to re-open.

**Closed by eteran** 2016-12-08 22:00 UTC

**Comment by eteran** [comment] 2017-04-24 16:22
I believe that this is now fixed!

**Comment by Shadowblitz16** [comment] 2020-08-11 00:22
@eteran I am getting this with Ubuntu 20.04.1 LTS
not sure if its the same issue but I followed the steps install the dependencies and to compile with cmake
