### ISSUE TITLE
Issues in compliation - Ubuntu 14.04

### ISSUE THREAD

**Issue by makflwana** [eteran/edb-debugger#439] opened 2016-07-27 04:09 UTC
Having some issues in compilation. following the instructions but issue comes with 'make'

Error : 

make: *** No targets specified and no makefile found.  Stop.

In the instructions or wiki there is no mention about this. Can you please assist.

Regards
FL

**Comment by eteran** [comment] 2016-07-27 04:18
can you please provide an exact listing of the commands you ran to get this error? Also, if you could provide more of the error log that would be helpful as well.

**Comment by makflwana** [comment] 2016-07-27 06:53
followed the instructions in wiki for Ubuntu>=13 as running Ubuntu 14.04
```
git clone --recursive https://github.com/eteran/edb-debugger.git
cd edb-debugger
mkdir build
cd build
cmake ..
```
Everything worked till this

When fire this command I get the original error - Will send the log file asap
make
./edb

**Comment by eteran** [comment] 2016-07-27 11:33
OK, all of that looks find so far, when you can send the full build log then I'll be able to diagnose more.

**Comment by 10110111** [comment] 2016-08-01 05:26
`cmake` command must have printed some errors which are fatal to configuration, thus no `Makefile` was generated. You'll have to correct these errors (which are likely missing packages) before you're able to compile.

**Comment by eteran** [comment] 2016-08-04 00:18
closing due to lack of follow up by original poster. @makflwana, if you like, feel free to re-open if this continues to be an issue and you have more information for us to reproduce.

**Closed by eteran** 2016-08-04 00:18 UTC
