### ISSUE TITLE
Analyzer cannot find bounds of heap

### ISSUE THREAD

**Issue by keantoken** [eteran/edb-debugger#576] opened 2017-08-01 18:03 UTC
I am getting this error on one of my (admittedly terrible) FASM programs. Is there something I'm doing that may be causing this or if it's something else. I am using the very latest 4.13 kernel to support some of my hardware. I notice this in the terminal:

[Heap Analyzer] __curbrk symbol not found in libc, falling back on heuristic! This may or may not work. 
[Heap Analyzer] __curbrk symbol not found in ld, falling back on heuristic! This may or may not work.

**Comment by eteran** [comment] 2017-08-01 18:16
Those messages are not necessarily fatal, however, the heap analyzer is not expected to work in 100% of all cases.

If you attach the source fasm file to this issue, I can try to reproduce and figure out why analysis has failed, and if it is possible to get it to work.

**Comment by keantoken** [comment] 2017-08-01 18:24
Here is the source and a binary. This version doesn't work, hence EDB. I can give you a working one if you want.
[AACircle.zip](https://github.com/eteran/edb-debugger/files/1191539/AACircle.zip)

**Comment by eteran** [comment] 2017-08-01 20:06
So, a few things:

1. The heap analyzer is only aware of the allocator used by Linux (doug lea's malloc and related). It doesn't seem like your code links to libc, so I don't think you are using it.

2. I don't see any usage of `mmap` or `brk` which are Linux's mechanisms for raw heap allocations. So I'm not sure what heap operations you are expecting to see.

3. throughout the execution (up to the crash) of the program, I never see a `[heap]` memory region created with confirms item 2.

Can you elaborate on what you are expecting to see and why?

**Comment by eteran** [comment] 2017-08-01 20:14
Looking at the actual source code: I do see things like `ImgAlloc`, which claim to do a `sys_mmap`. So assuming that those are actually code, there **should** be heap stuff, but it doesn't seem to be actually happening.

**Comment by eteran** [comment] 2017-08-01 20:24
Yea, I take back (most of) my original comments, the code is definitely trying to do some dynamic allocation via mmap (attached screenshot for personal and shared reference).

But as stated before, edb won't have any understanding of the structure of the heap since you aren't using a standard allocator.

Also, it does seem that this program is doing some wierd stuff with `rflags` it occasionally breaks the ability to properly continue (I am guessing that it is somehow setting the step bit in the flags manually).


![screenshot_20170801_162118](https://user-images.githubusercontent.com/571477/28845329-a47d7bb4-76d5-11e7-9fcd-44d6c102d216.png)

**Comment by eteran** [comment] 2017-08-01 20:27
As a note, the `mmap` allocation is successful, but the system doesn't mark it as part of the `[heap]` memory region. Which is why edb doesn't find it.

I am going to close this issue, because edb's heap analyzer cannot analyze custom heap structures.

Let me know if there is anything else I can help with.

![screenshot_20170801_162504](https://user-images.githubusercontent.com/571477/28845478-302d3b72-76d6-11e7-9a75-f4ff13834f2d.png)

**Closed by eteran** 2017-08-01 20:27 UTC

**Comment by keantoken** [comment] 2017-08-01 20:30
That's fine. Here is a working version if it will clarify anything, but I think you're right.

[AACircle11.4.zip](https://github.com/eteran/edb-debugger/files/1191824/AACircle11.4.zip)
