### ISSUE TITLE
./edb --run cat smoke.txt | ./bufbomb -u llll

### ISSUE THREAD

**Issue by YuxuanXie** [eteran/edb-debugger#706] opened 2019-04-13 05:10 UTC
When i start edb by this command, edb can not be open. How can I make it? Thank you very much

**Comment by eteran** [comment] 2019-04-14 02:54
Right, so this requires a feature not quite implemented yet :-/ See issue #627 .

I plan to implement such a feature sometime, hopefully, sooner than later since it seems to be one that several people would find useful.

Closing as a duplicate of #627, but still VERY much on my radar to implement.

**Closed by eteran** 2019-04-14 02:54 UTC
