### ISSUE TITLE
Dark Theme doesn't work for me

### ISSUE THREAD

**Issue by ghost** [eteran/edb-debugger#436] opened 2016-07-13 16:21 UTC
Hi. Continuous reading for a long time is annoying and can damage the eyes. 
Would it be possible theme Dark version or the ability to change colors in settings?. Thanks.

**Comment by zebus3d** [comment] 2016-07-13 16:56
https://github.com/eteran/edb-debugger/wiki/Theming

Solved Soryy.

**Comment by eteran** [comment] 2016-07-15 02:02
Hmm, the dark theme isn't perfect, but it should work at least mostly. I'll give it a try right now and see if it works for me.

**Comment by eteran** [comment] 2016-07-15 02:06
OK, I think I know what the issue is. edb uses the system settings for the core palette. The stuff in the conf file covers what isn't covered by your window manager. Perhaps we can add an override for this. But for starters, you may want to try setting your WM to use a dark theme and then go from there.

**Comment by keantoken** [comment] 2017-07-10 04:49
I definitely want a working dark theme too, but dark themes are usually broken in some way for whatever distro you use (there is some critical program somewhere which will still use black text on the dark background specified in your system palette). System palette should probably be turned off when using a custom theme.

**Comment by eteran** [comment] 2017-07-10 05:47
@keantoken you are right. We should offer a full override when using a theme. I'll try to add coverage to the little details sometime so that we can get a better look on dark themed desktops :-)

**Comment by keantoken** [comment] 2017-07-10 07:52
One version of Gedit I used had an option to choose whether or not to use the system's GTK+ palette, which might be good for reference. Unfortunately popular GTK apps seem to be constantly under the knife with features being added and removed every year, which is infuriating. There was one version of Calc I liked, but eventually got lost in the continual distro facelift carnival ride.

**Comment by 10110111** [comment] 2017-07-10 08:19
Well, GTK+ is a bad example to follow, in any case. They [remove features](https://bugzilla.gnome.org/show_bug.cgi?id=735211 in the semi-minor upgrades), [force views of GNOME on standalone GTK+ users](https://github.com/PCMan/gtk3-nocsd), in general [have bad accessibility](https://igurublog.wordpress.com/2014/03/22/gtk-3-10-drops-menu-icons-and-mnemonics/) at least by default.

Some Qt-based apps though also allow changing color scheme in themselves, I just have to recall which (TeXstudio and MuseScore come to mind, but they are not quite what I really want to recall in this context).

**Comment by kdre** [comment] 2017-10-20 14:03
I also have troubles with the colors in general.

* "call ld-2.25.so!_dl_start"
The number (2.25) is white, while ld- and .so!_dl_start is in a dark blue.
This sees like a bug to me?

* Commas are in dark blue as well as the word "rel" and square brackets ([]).

I did not find out how to change the dark blue parts, no matter which theme I am using.

Any ideas?

**Comment by ped7g** [comment] 2018-05-05 08:58
I have KDE-neon distribution in default dark theme, and edb is usable, but some colours (intensive dark blue on instructions, black arguments) and icons (black on gray) are difficult to see, I'm adding screenshot of v1.0.0 with default config (no theme property modified):

<img width="777" alt="screenshot_20180505_edb" src="https://user-images.githubusercontent.com/236664/39661502-baf40a00-5052-11e8-8606-56398d23f136.png">

I wonder where these default colours come from, is it like the edb has in source code some partial defaults, mixing them with the system defaults? Where should I look? Maybe there's some possibility to create some heuristic based on system colour of background to set remaining specialized colours from one of the two sets to maintain good contrast.

**Comment by ped7g** [comment] 2018-05-05 09:12
And now I tried the wiki/Theming dark theme in configuration, and the blue things in memory view and for some instructions remain, but I don't see how that can be configured through the `[Theme]` config, maybe the wiki page is out of sync with sources?

**Comment by eteran** [comment] 2018-05-05 12:46
Yea, we definitely need to add hooks to theme those last few things which don't go well with a dark theme. The wiki is up to date with the sources, unfortunately, you've run into a few of the hardcoded colors. We'll work on making them themable too :-).

**Comment by eteran** [comment] 2020-12-21 03:44
Should be fixed in master (and 1.3.0). How you can explicitly choose dark and light themes as well as providing your own :-).

**Closed by eteran** 2020-12-21 03:44 UTC
Labels: question
