### ISSUE TITLE
edb Failed to load a necessary plugin

### ISSUE THREAD

**Issue by Fetchered** [eteran/edb-debugger#350] opened 2016-02-07 18:21 UTC
"Failed to successfully load the debugger core plugin." I've placed the libDebuggerCore.so file in just about every directory on my machine, and changed the plugin directory to match. Other plugins still pop up in the plugins tab (Analyzer,Assembly,BinaryInfo, and Check Version), but not the debugger core.

Ubuntu 14.04, SIFT workstation, file located in /home/sansforensics/edb-debugger/ and /home/sansforensics/edb-debugger/plugins and /home/sansforensics/edb-debugger/plugins/DebuggerCore/

Current plugin directory is set to /home/sansforensics/edb-debugger/ and that is the only directory location that seems to pick up the other plugins. If I change it to anything else, it doesn't pick up any of the other plugins above.

Any thoughts?

**Comment by eteran** [comment] 2016-02-08 15:30
Any chance that you've done a build in the same directory as a previous one? If you updated the sources, and for some reason the DebuggerCore plugin didn't get rebuilt, then it may fail to load.

So here's some things I would try:

1. make sure you're using the latest from master, a lot has been improved since the last release :-).
2. If you are building using `qmake`, try a `make distclean` then the typical `qmake && make`
3. If you are building using `cmake`, make sure to blow away the old build directory, then `mkdir build && cd build && cmake .. && make`

Let me know if you have any luck.

**Comment by Fetchered** [comment] 2016-02-08 16:46
I'll give it a shot this afternoon when I get back to that machine.
Thanks!

**Comment by eteran** [comment] 2016-02-22 15:59
It has been 2 weeks since the last update from @Fetchered, so I am assuming that the full rebuild was successful.

Please re-open if this this not the case.

**Comment by rbenlizar** [comment] 2016-09-10 04:43
I found another solution to this. When the popup windows shows up; scroll over to the "Directories" tab and make the following correction

Symbol Directory - <path to the directory folder>
Plugin Directory - /lib64/edb/
Session Directory - <path to the directory folder>

**Comment by eteran** [comment] 2016-09-12 16:47
@rbenlizar Right, generally speaking, the "Plugin Directory" should be where the binaries for the various plugins have been installed. This is typically `$INSTALL_PREFIX/lib64/edb` on amd64 systems.

Alternatively, if you choose not to "install", edb is content to run out of the build directory, you just need to be sure that the Plugin Directory is set to where the build was done.

Thanks!

**Comment by jmarshall120** [comment] 2016-10-21 09:56
I'm having the same issue as reported by @Fetchered. The plugin directory is correctly input in the popup window, the other plugins are displayed in the 'plugins' tab but the same error continually comes up.

**Comment by 10110111** [comment] 2016-10-21 10:05
@jmarshall120  what does EDB print in the console? Sometimes console log has more useful information than user-visible dialog.
@eteran: it seems failures to load plugins should be made user-visible, at least in such cases.

**Comment by jmarshall120** [comment] 2016-10-23 06:07
I'm not getting any errors in the terminal. I also tried passing edb to stderr and stdout and reading those but that unfortunately also didn't work.

**Comment by mipko** [comment] 2016-11-20 00:53
latest clone from GIT, compiled and getting these errors when tried to start edb

[load_plugins] Cannot load library /home/mirko/programiranje/debugger/libAnalyzer.so: (/home/mirko/programiranje/debugger/libAnalyzer.so: undefined symbol: _ZN8edisassm11InstructionINS_6x86_64EE14Opcode_invalidE)
[load_plugins] Cannot load library /home/mirko/programiranje/debugger/libAssembler.so: (/home/mirko/programiranje/debugger/libAssembler.so: undefined symbol: _ZN8edisassm11InstructionINS_6x86_64EE14Opcode_invalidE)
[load_plugins] Cannot load library /home/mirko/programiranje/debugger/libBreakpointManager.so: (/home/mirko/programiranje/debugger/libBreakpointManager.so: undefined symbol: _ZN3edb2v19get_valueEyPbP15ExpressionError)
[load_plugins] Cannot load library /home/mirko/programiranje/debugger/libDumpState.so: (/home/mirko/programiranje/debugger/libDumpState.so: undefined symbol: _ZN8edisassm11InstructionINS_6x86_64EE14Opcode_invalidE)
[load_plugins] Cannot load library /home/mirko/programiranje/debugger/libOpcodeSearcher.so: (/home/mirko/programiranje/debugger/libOpcodeSearcher.so: undefined symbol: _ZN8edisassm11InstructionINS_6x86_64EE14Opcode_invalidE)
[load_plugins] Cannot load library /home/mirko/programiranje/debugger/libReferences.so: (/home/mirko/programiranje/debugger/libReferences.so: undefined symbol: _ZN8edisassm11InstructionINS_6x86_64EE14Opcode_invalidE)
[load_plugins] Cannot load library /home/mirko/programiranje/debugger/libROPTool.so: (/home/mirko/programiranje/debugger/libROPTool.so: undefined symbol: _ZN8edisassm11InstructionINS_6x86_64EE14Opcode_invalidE)

**Comment by eteran** [comment] 2016-11-20 01:11
@mipko

Looks like it is trying to load an old version of the plugins. Try setting the directory in the settings

**Comment by mipko** [comment] 2016-11-20 08:37
@eteran
This is the only edb version I have at the computer. How can I edit settings?

**Comment by pjackowski** [comment] 2017-04-23 18:04
I am having same issue: Failed to successfully load the debugger core plugin. Please make sure it exists and that the plugin path is correctly configured.

I had compiled edb from git sources, after cloning with --recursive as recommended. First when I got error, I changed paths in Directories tab, and run again from build directory with plugins and executable in it. This didn't work, so I decided to make install, and change path in Directories tab to /usr/local/lib64/edb. Still no luck. Tried to run it as root, and regular user. There are no SELinux alerts. Config is preserved, as it remains to what I had changed before. Paths to plugins were correct, they point to existing directories with compiled libDebuggerCore.so file (and other libs).

Not sure what to do, apart from downloading Linux distro with edb pre-installed.

**Comment by eteran** [comment] 2017-04-23 18:06
I am going to make replicating and fixing this issue a top priority as it seems that several users are effected now.

Thanks for the information.

**Comment by eteran** [comment] 2017-04-24 16:23
I believe that this is now fixed!

**Closed by eteran** 2017-04-24 16:23 UTC

**Comment by pjackowski** [comment] 2017-04-25 12:02
@eteran

I can confirm issue is now fixed. Thanks! ;-)

**Comment by akshanshshrivastava** [comment] 2017-09-25 08:32
The path to my plugin was > /usr/lib/x86_64-gnu/edb
I change it to > /usr/lib/x86_64-linux-gnu/edb
Worked for me.

**Comment by Clutchisback1** [comment] 2018-08-14 18:17
Thanks! I went into the edb preferences and went to one of the tabs and changed it from:
/usr/lib/edb

to:

/usr/lib/x86_64-linux-gnu/edb

**Comment by sebsmith20** [comment] 2018-10-29 20:15
I am having the same issue, i have installed EDB and i cant find the debugger core plugin. Is the core plugin in the Cmake folder?

**Comment by eteran** [comment] 2018-10-29 21:19
@sebsmith20, did you check the plug-in path in the preferences?

**Comment by 10110111** [comment] 2018-10-30 10:39
@sebsmith20 Are you on Windows? EDB doesn't use `execv` on Windows...
And on other platforms Windows programs are normally run using Wine, which is not too easy to make interact with EDB.

**Comment by sebsmith20** [comment] 2018-10-30 10:42
i am on kali linux. Ye i have wine installed on my kali. buts its when i am trying to open the .exe file in EDB it wont allow me to

**Comment by 10110111** [comment] 2018-10-30 10:49
It's Linux which won't allow you to. At the very least an executable must be executable (have the `x` bit set in the permissions). But if you don't have corresponding `binfmt_misc` support for PE files, this will still be useless.
And in any case, debugging Wine-driven apps in EDB needs lots of work. You must know exactly what you're doing if you attempt to do this.

**Comment by 4A47** [comment] 2019-05-07 00:16
Same problem, prompted to set the plugin directory which I do, edb then forces to restart and doesnt remember that the directory has been changed.

**Comment by RA-46** [comment] 2019-12-06 06:16
What worked for me was uninstalling edb version 1.0 (older version) dpkg --list showed
edb-debugger                              1.0.0-1+b2                          
edb-debugger-plugins:amd64                1.0.0-1+b2
removed them by using sudo apt-get --purge remove  (pkg name)
then was able to run edb
