### ISSUE TITLE
RENAME

### ISSUE THREAD

**Issue by b0t0w1** [eteran/edb-debugger#541] opened 2017-02-24 01:32 UTC
How to rename the executable file "edb"?

**Comment by AaronOpfer** [comment] 2017-02-24 05:49
Does doing `mv edb someothername` after the build is complete not work the way you expect?

**Comment by eteran** [comment] 2017-02-27 16:34
@b0t0w1 We are going to need you to be a little more specific about your issue. I am going to quote the email you wrote to me a few days ago for context:

> Hi~，I use the edb-debugger. It is very nice. But when I rename the executable file "edb" and start debugger, it can not find the "MainSymbol". Could you tell me how to change the file name correctly
> 
> Thank you!

Please clarify the following:

1. Are you renaming the edb executable itself? (Why?) 
2. Does mv edb edb.new not work?
3. Does it complains about not finding the "MainSymbol", is this when attaching? 
4. Does it otherwise function correctly?

Let us know and we'll do our best to get the bottom of it.

**Comment by b0t0w1** [comment] 2017-03-03 00:49
I mv edb edb.new but it not work. I find it can not find the
mainsymbol("test!main"). But yesterday I do my work to start over again, it
succeed. I do no not know why. Maybe I change something else. Sorry to
disturb you.

2017-02-28 0:34 GMT+08:00 Evan Teran <notifications@github.com>:

**Comment by eteran** [comment] 2017-03-03 00:59
OK, I'll close this for now since we can't reproduce it, but feel free to reopen if needed.

**Closed by eteran** 2017-03-03 00:59 UTC
