### ISSUE TITLE
Save Changed File

### ISSUE THREAD

**Issue by emrecpp** [eteran/edb-debugger#570] opened 2017-07-18 07:09 UTC
Hello!
I know reverse engineering. I am new in Linux. I changed "cmp eax, 0" to "cmp eax, 1"  and it worked. 
So I should save this file but how?
Thanks :)

**Comment by eteran** [comment] 2017-07-18 11:35
edb does not currently have such a feature to save changes back made in memory to an executable on disk, but we'd like to have it. It is a planned feature for some point in the future.

This is a duplicate of #127 so closing. Please follow that issue for future updates on this feature :-)

**Closed by eteran** 2017-07-18 11:35 UTC
