### ISSUE TITLE
Error: Failed to open and attach to process: execv() failed: permission denied

### ISSUE THREAD

**Issue by yanbrasiliano** [eteran/edb-debugger#803] opened 2021-04-21 22:18 UTC
Hello there! 
I am trying to open an .exe file in my edb but the following error returns: 

Failed to open and attach to process: execv() failed: permission denied

![image](https://user-images.githubusercontent.com/72168914/115627281-1b9deb00-a2d5-11eb-8584-1568178d10f7.png)

System: Kubuntu 20.4
Kernel: 5.8.0-50 generic

**Comment by 10110111** [comment] 2021-04-22 06:38
Windows executables in Linux normally run via Wine, so direct execution via `execve` won't work. I don't think EDB will work in this case. You might try starting the process without EDB, and then attaching to it, if your use case allows this.

**Comment by yanbrasiliano** [comment] 2021-04-22 11:14
in this case, compiling the source code on Linux would you be able to open it?

**Comment by 10110111** [comment] 2021-04-22 16:02
> compiling the source code on Linux

The main point is to compile _for_ Linux, not necessarily _on_ it. If you compile it for Linux, then yes, EDB should run it.

**Comment by eteran** [comment] 2021-04-24 17:28
Closing since I believe the issue is identified. Windows executables are not executable under Linux (outside of things like wine). Since EDB doesn't itself run executables and just asks the OS to run the target, EDB cannot debug those directly either.

It is possible in principle to debug a Windows executable by running it in wine, and then attaching to that instance of wine... but I doubt the experience would be pleasant.

**Closed by eteran** 2021-04-24 17:28 UTC

**Comment by eteran** [comment] 2021-04-26 14:44
Also, since this has come up a few times before, I've added a new FAQ section to the WIKI.

https://github.com/eteran/edb-debugger/wiki/FAQ

@10110111 Feel free to clarify the language on it if you think it can be explained better :-)
