### ISSUE TITLE
no matching function for call to ‘find(std::array<const char*, 6ul>::const_iterator, const char* const* const&, const QString&)’

### ISSUE THREAD

**Issue by FaizSayyid** [eteran/edb-debugger#272] opened 2015-10-13 18:55 UTC
Hi,

I've been trying to compile edb - I've worked through a few issues - this one is the latest.

    unix/linux/PlatformState.cpp: In member function ‘virtual Register DebuggerCore::PlatformState::value(const QString&) const’:
    unix/linux/PlatformState.cpp:719:80: error: no matching function for call to ‘find(std::array<const char*, 6ul>::const_iterator, const char* const* const&, const QString&)’
    const auto regNameFoundIter=std::find(x86.segRegNames.begin(),end,segRegName);

Does anyone know how I can proceed?

Thanks very much

**Comment by 10110111** [comment] 2015-10-13 19:01
Are you using an old version of compiler? Try explicitly specifying `std::array::const_iterator` instead of `auto` in the declaration of `end`.

**Comment by FaizSayyid** [comment] 2015-10-13 19:39
hey, yeah i'm on:
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)

Now is get unix/linux/PlatformState.cpp:685:8: error: invalid use of template-name ‘std::array’ without an argument list
  const std::array::const_iterator end=names.begin()+maxNames;

thanks

**Comment by eteran** [comment] 2015-10-13 19:58
@FaizSayyid do you have the latest checked out. That line looks like this in my latest master:

    const auto end=names.begin()+maxNames;

**Comment by eteran** [comment] 2015-10-13 20:00
so it seems to think that `end` and `names.begin()` are different types, which is weird. Looking into it.

**Comment by eteran** [comment] 2015-10-13 20:07
@FaizSayyid, we got bit by HTML + markdown removing some stuff: Please try this change:

    const auto end=names.begin()+maxNames;

to:

    typename Names::const_iterator end=names.begin()+maxNames;

I think you've got a possibly broken version of libstd++ where `std::array<const char *, N>::iterator` decays to `const char **` when assigned to `auto`?

**Comment by eteran** [comment] 2015-10-13 20:07
let me know if that works, if so, I'll commit that fix to master with a note

**Comment by FaizSayyid** [comment] 2015-10-13 20:16
Hi @eteran 

I still get:

nix/linux/PlatformState.cpp: In member function ‘virtual Register DebuggerCore::PlatformState::value(const QString&) const’:
unix/linux/PlatformState.cpp:719:80: error: no matching function for call to ‘find(std::array<const char*, 6ul>::const_iterator, const char* const* const&, const QString&)’
    const auto regNameFoundIter=std::find(x86.segRegNames.begin(),end,segRegName);

Thanks very much for trying to help me!

**Comment by eteran** [comment] 2015-10-13 20:22
ok, same error different line, can you apply a similar fix to line **719** ?

    std::array<const char*,MAX_SEG_REG_COUNT>::const_iterator end = x86.segRegNames.end();

what you should change it to

**Comment by eteran** [comment] 2015-10-13 20:25
and I predict you needing to do it to line **988** as well:

    std::array<const char*,MAX_GPR_COUNT>::const_iterator gpr_end=GPRegNames().begin()+gpr_count();

**Comment by FaizSayyid** [comment] 2015-10-13 20:35
Hey, I have made the changes. Now i get these errors:

unix/linux/PlatformState.cpp: In member function ‘virtual Register DebuggerCore::PlatformState::value(const QString&) const’:
unix/linux/PlatformState.cpp:720:80: error: no matching function for call to ‘find(std::array<const char*, 6ul>::const_iterator, const char* const*&, const QString&)’
    const auto regNameFoundIter=std::find(x86.segRegNames.begin(),end,segRegName);
                                                                                ^
unix/linux/PlatformState.cpp:720:80: note: candidate is:
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/locale_facets.h:48:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/basic_ios.h:37,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ios:44,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ostream:38,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/iterator:64,
                 from /usr/include/QtCore/qlist.h:50,
                 from /usr/include/QtCore/qvariant.h:47,
                 from /usr/include/QtCore/QVariant:1,
                 from ../../include/Types.h:25,
                 from ../../include/IState.h:22,
                 from unix/linux/PlatformState.h:22,
                 from unix/linux/PlatformState.cpp:19:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
unix/linux/PlatformState.cpp:720:80: note:   mismatched types ‘std::istreambuf_iterator<_CharT>’ and ‘const char* const*’
    const auto regNameFoundIter=std::find(x86.segRegNames.begin(),end,segRegName);
                                                                                ^
unix/linux/PlatformState.cpp: In member function ‘virtual void DebuggerCore::PlatformState::set_register(const Register&)’:
unix/linux/PlatformState.cpp:989:74: error: no matching function for call to ‘find(std::array<const char*, 16ul>::const_iterator, const char* const*&, const QString&)’
  auto GPRegNameFoundIter=std::find(GPRegNames().begin(), gpr_end, regName);
                                                                          ^
unix/linux/PlatformState.cpp:989:74: note: candidate is:
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/locale_facets.h:48:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/basic_ios.h:37,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ios:44,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ostream:38,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/iterator:64,
                 from /usr/include/QtCore/qlist.h:50,
                 from /usr/include/QtCore/qvariant.h:47,
                 from /usr/include/QtCore/QVariant:1,
                 from ../../include/Types.h:25,
                 from ../../include/IState.h:22,
                 from unix/linux/PlatformState.h:22,
                 from unix/linux/PlatformState.cpp:19:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
unix/linux/PlatformState.cpp:989:74: note:   mismatched types ‘std::istreambuf_iterator<_CharT>’ and ‘const char* const*’
  auto GPRegNameFoundIter=std::find(GPRegNames().begin(), gpr_end, regName);
                                                                          ^
unix/linux/PlatformState.cpp:996:92: error: no matching function for call to ‘find(std::array<const char*, 6ul>::const_iterator, std::array<const char*, 6ul>::const_iterator, const QString&)’
  auto segRegNameFoundIter=std::find(x86.segRegNames.begin(), x86.segRegNames.end(), regName);
                                                                                            ^
unix/linux/PlatformState.cpp:996:92: note: candidate is:
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/locale_facets.h:48:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/basic_ios.h:37,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ios:44,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ostream:38,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/iterator:64,
                 from /usr/include/QtCore/qlist.h:50,
                 from /usr/include/QtCore/qvariant.h:47,
                 from /usr/include/QtCore/QVariant:1,
                 from ../../include/Types.h:25,
                 from ../../include/IState.h:22,
                 from unix/linux/PlatformState.h:22,
                 from unix/linux/PlatformState.cpp:19:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
unix/linux/PlatformState.cpp:996:92: note:   mismatched types ‘std::istreambuf_iterator<_CharT>’ and ‘const char* const*’
  auto segRegNameFoundIter=std::find(x86.segRegNames.begin(), x86.segRegNames.end(), regName);
                                                                                            ^
unix/linux/PlatformState.cpp: In instantiation of ‘Register DebuggerCore::findRegisterValue(const Names&, const Regs&, const QString&, Register::Type, std::size_t, int) [with long unsigned int bitSize = 0ul; Names = std::array<const char*, 16ul>; Regs = std::array<edb::address_t, 16ul>; std::size_t = long unsigned int]’:
unix/linux/PlatformState.cpp:704:137:   required from here
unix/linux/PlatformState.cpp:686:59: error: no matching function for call to ‘find(std::array<const char*, 16ul>::const_iterator, const char* const*&, const QString&)’
  auto regNameFoundIter=std::find(names.begin(),end,regName);
                                                           ^
unix/linux/PlatformState.cpp:686:59: note: candidate is:
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/locale_facets.h:48:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/basic_ios.h:37,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ios:44,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ostream:38,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/iterator:64,
                 from /usr/include/QtCore/qlist.h:50,
                 from /usr/include/QtCore/qvariant.h:47,
                 from /usr/include/QtCore/QVariant:1,
                 from ../../include/Types.h:25,
                 from ../../include/IState.h:22,
                 from unix/linux/PlatformState.h:22,
                 from unix/linux/PlatformState.cpp:19:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
unix/linux/PlatformState.cpp:686:59: note:   mismatched types ‘std::istreambuf_iterator<_CharT>’ and ‘const char* const*’
  auto regNameFoundIter=std::find(names.begin(),end,regName);
                                                           ^
unix/linux/PlatformState.cpp: In instantiation of ‘Register DebuggerCore::findRegisterValue(const Names&, const Regs&, const QString&, Register::Type, std::size_t, int) [with long unsigned int bitSize = 32ul; Names = std::array<const char*, 16ul>; Regs = std::array<edb::address_t, 16ul>; std::size_t = long unsigned int]’:
unix/linux/PlatformState.cpp:706:107:   required from here
unix/linux/PlatformState.cpp:686:59: error: no matching function for call to ‘find(std::array<const char*, 16ul>::const_iterator, const char* const*&, const QString&)’
unix/linux/PlatformState.cpp:686:59: note: candidate is:
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/locale_facets.h:48:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/basic_ios.h:37,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ios:44,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ostream:38,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/iterator:64,
                 from /usr/include/QtCore/qlist.h:50,
                 from /usr/include/QtCore/qvariant.h:47,
                 from /usr/include/QtCore/QVariant:1,
                 from ../../include/Types.h:25,
                 from ../../include/IState.h:22,
                 from unix/linux/PlatformState.h:22,
                 from unix/linux/PlatformState.cpp:19:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
unix/linux/PlatformState.cpp:686:59: note:   mismatched types ‘std::istreambuf_iterator<_CharT>’ and ‘const char* const*’
  auto regNameFoundIter=std::find(names.begin(),end,regName);
                                                           ^
unix/linux/PlatformState.cpp: In instantiation of ‘Register DebuggerCore::findRegisterValue(const Names&, const Regs&, const QString&, Register::Type, std::size_t, int) [with long unsigned int bitSize = 16ul; Names = std::array<const char*, 16ul>; Regs = std::array<edb::address_t, 16ul>; std::size_t = long unsigned int]’:
unix/linux/PlatformState.cpp:708:107:   required from here
unix/linux/PlatformState.cpp:686:59: error: no matching function for call to ‘find(std::array<const char*, 16ul>::const_iterator, const char* const*&, const QString&)’
unix/linux/PlatformState.cpp:686:59: note: candidate is:
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/locale_facets.h:48:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/basic_ios.h:37,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ios:44,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ostream:38,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/iterator:64,
                 from /usr/include/QtCore/qlist.h:50,
                 from /usr/include/QtCore/qvariant.h:47,
                 from /usr/include/QtCore/QVariant:1,
                 from ../../include/Types.h:25,
                 from ../../include/IState.h:22,
                 from unix/linux/PlatformState.h:22,
                 from unix/linux/PlatformState.cpp:19:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
unix/linux/PlatformState.cpp:686:59: note:   mismatched types ‘std::istreambuf_iterator<_CharT>’ and ‘const char* const*’
  auto regNameFoundIter=std::find(names.begin(),end,regName);
                                                           ^
unix/linux/PlatformState.cpp: In instantiation of ‘Register DebuggerCore::findRegisterValue(const Names&, const Regs&, const QString&, Register::Type, std::size_t, int) [with long unsigned int bitSize = 8ul; Names = std::array<const char*, 16ul>; Regs = std::array<edb::address_t, 16ul>; std::size_t = long unsigned int]’:
unix/linux/PlatformState.cpp:710:122:   required from here
unix/linux/PlatformState.cpp:686:59: error: no matching function for call to ‘find(std::array<const char*, 16ul>::const_iterator, const char* const*&, const QString&)’
unix/linux/PlatformState.cpp:686:59: note: candidate is:
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/locale_facets.h:48:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/basic_ios.h:37,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ios:44,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ostream:38,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/iterator:64,
                 from /usr/include/QtCore/qlist.h:50,
                 from /usr/include/QtCore/qvariant.h:47,
                 from /usr/include/QtCore/QVariant:1,
                 from ../../include/Types.h:25,
                 from ../../include/IState.h:22,
                 from unix/linux/PlatformState.h:22,
                 from unix/linux/PlatformState.cpp:19:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
unix/linux/PlatformState.cpp:686:59: note:   mismatched types ‘std::istreambuf_iterator<_CharT>’ and ‘const char* const*’
  auto regNameFoundIter=std::find(names.begin(),end,regName);
                                                           ^
unix/linux/PlatformState.cpp: In instantiation of ‘Register DebuggerCore::findRegisterValue(const Names&, const Regs&, const QString&, Register::Type, std::size_t, int) [with long unsigned int bitSize = 8ul; Names = std::array<const char*, 4ul>; Regs = std::array<edb::address_t, 16ul>; std::size_t = long unsigned int]’:
unix/linux/PlatformState.cpp:712:126:   required from here
unix/linux/PlatformState.cpp:686:59: error: no matching function for call to ‘find(std::array<const char*, 4ul>::const_iterator, const char* const*&, const QString&)’
unix/linux/PlatformState.cpp:686:59: note: candidate is:
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/locale_facets.h:48:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/basic_ios.h:37,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ios:44,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ostream:38,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/iterator:64,
                 from /usr/include/QtCore/qlist.h:50,
                 from /usr/include/QtCore/qvariant.h:47,
                 from /usr/include/QtCore/QVariant:1,
                 from ../../include/Types.h:25,
                 from ../../include/IState.h:22,
                 from unix/linux/PlatformState.h:22,
                 from unix/linux/PlatformState.cpp:19:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
unix/linux/PlatformState.cpp:686:59: note:   mismatched types ‘std::istreambuf_iterator<_CharT>’ and ‘const char* const*’
  auto regNameFoundIter=std::find(names.begin(),end,regName);
                                                           ^
unix/linux/PlatformState.cpp: In instantiation of ‘Register DebuggerCore::findRegisterValue(const Names&, const Regs&, const QString&, Register::Type, std::size_t, int) [with long unsigned int bitSize = 0ul; Names = std::array<const char*, 6ul>; Regs = std::array<edb::detail::SizedValue<16>, 6ul>; std::size_t = long unsigned int]’:
unix/linux/PlatformState.cpp:714:107:   required from here
unix/linux/PlatformState.cpp:686:59: error: no matching function for call to ‘find(std::array<const char*, 6ul>::const_iterator, const char* const*&, const QString&)’
unix/linux/PlatformState.cpp:686:59: note: candidate is:
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/locale_facets.h:48:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/basic_ios.h:37,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ios:44,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ostream:38,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/iterator:64,
                 from /usr/include/QtCore/qlist.h:50,
                 from /usr/include/QtCore/qvariant.h:47,
                 from /usr/include/QtCore/QVariant:1,
                 from ../../include/Types.h:25,
                 from ../../include/IState.h:22,
                 from unix/linux/PlatformState.h:22,
                 from unix/linux/PlatformState.cpp:19:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note: template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)
     find(istreambuf_iterator<_CharT> __first,
     ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/streambuf_iterator.h:369:5: note:   template argument deduction/substitution failed:
unix/linux/PlatformState.cpp:686:59: note:   mismatched types ‘std::istreambuf_iterator<_CharT>’ and ‘const char* const*’
  auto regNameFoundIter=std::find(names.begin(),end,regName);
                                                           ^
unix/linux/PlatformState.cpp: In function ‘Register DebuggerCore::findRegisterValue(const Names&, const Regs&, const QString&, Register::Type, std::size_t, int) [with long unsigned int bitSize = 0ul; Names = std::array<const char*, 16ul>; Regs = std::array<edb::address_t, 16ul>; std::size_t = long unsigned int]’:
unix/linux/PlatformState.cpp:691:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
unix/linux/PlatformState.cpp: In function ‘Register DebuggerCore::findRegisterValue(const Names&, const Regs&, const QString&, Register::Type, std::size_t, int) [with long unsigned int bitSize = 32ul; Names = std::array<const char*, 16ul>; Regs = std::array<edb::address_t, 16ul>; std::size_t = long unsigned int]’:
unix/linux/PlatformState.cpp:691:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
unix/linux/PlatformState.cpp: In function ‘Register DebuggerCore::findRegisterValue(const Names&, const Regs&, const QString&, Register::Type, std::size_t, int) [with long unsigned int bitSize = 16ul; Names = std::array<const char*, 16ul>; Regs = std::array<edb::address_t, 16ul>; std::size_t = long unsigned int]’:
unix/linux/PlatformState.cpp:691:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
unix/linux/PlatformState.cpp: In function ‘Register DebuggerCore::findRegisterValue(const Names&, const Regs&, const QString&, Register::Type, std::size_t, int) [with long unsigned int bitSize = 8ul; Names = std::array<const char*, 16ul>; Regs = std::array<edb::address_t, 16ul>; std::size_t = long unsigned int]’:
unix/linux/PlatformState.cpp:691:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
unix/linux/PlatformState.cpp: In function ‘Register DebuggerCore::findRegisterValue(const Names&, const Regs&, const QString&, Register::Type, std::size_t, int) [with long unsigned int bitSize = 8ul; Names = std::array<const char*, 4ul>; Regs = std::array<edb::address_t, 16ul>; std::size_t = long unsigned int]’:
unix/linux/PlatformState.cpp:691:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
unix/linux/PlatformState.cpp: In function ‘Register DebuggerCore::findRegisterValue(const Names&, const Regs&, const QString&, Register::Type, std::size_t, int) [with long unsigned int bitSize = 0ul; Names = std::array<const char*, 6ul>; Regs = std::array<edb::detail::SizedValue<16>, 6ul>; std::size_t = long unsigned int]’:
unix/linux/PlatformState.cpp:691:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^

**Comment by eteran** [comment] 2015-10-13 20:43
OK, the first error in that, is for line **720**, I'm assuming that matches my **719** (except for a difference in white space).

Please make sure to apply ALL the changes I've listed.

let me know

**Comment by FaizSayyid** [comment] 2015-10-13 20:56
I have applied all the changes, I still get exactly the same errors :(

**Comment by eteran** [comment] 2015-10-13 23:32
This line:

     const auto regNameFoundIter=std::find(x86.segRegNames.begin(),end,segRegName);

means that you have **not** applied all of the changes discussed. Please test to see if changing it to this works:

    std::array<const char*,MAX_SEG_REG_COUNT>::const_iterator end = x86.segRegNames.end();

**Comment by eteran** [comment] 2015-10-15 23:48
@FaizSayyid , if this solved your issue, please let us know so that we can update the status of this report. If not, can you specify which distribution and set of packages you have installed so we can try to replicate? Are you using RHEL/CentOS or Fedora? If so, which version? I'm not typically a redhat user so if you could point me at which repos and packages you installed to get gcc-4.8 that woudl be great too.

**Comment by eteran** [comment] 2015-12-04 17:29
So Here's the issue: `std::array<T,N>::const_iterator` is (in this case) implemented as a `typedef T*`. Unfortunately, one quirk of doing that is that the `operator+` of the iterator returns a `T*`, which the compiler sees a different type :-/.

So, the most portable solution is not to use `auto` here.  While I prefer to use `auto` for iterators, the portable solution is to be explicit.

**Comment by 10110111** [comment] 2015-12-04 18:47
Your explanation doesn't seem to make sense. A `typedef` is just an alias for the type, so for all purposes it's exactly the same, see this test:
````
#include <typeinfo>
#include <iostream>
#include <iomanip>

int main()
{
    typedef int mytype;
    std::cout << std::boolalpha << "mytype is int? "
              << (typeid(mytype)==typeid(int)) << "\n";
}
````

**Comment by eteran** [comment] 2015-12-04 20:41
Hmm, the issue does seem more nuanced than I described. I can't replicated it with trivial code :-/. However, I do think that it is something **like** what I described, if not exactly.

The reason why I believe this (and of course I could be wrong), is that naming the type as `std::array<const char*,MAX_SEG_REG_COUNT>::const_iterator` explicitly solves the problem for this user, `auto` doesn't work.

The error message is that there is no function `find(std::array<const char*, 6ul>::const_iterator, const char* const*&, const QString&)`

So the compiler seems to be considering `std::array<const char*, 6ul>::const_iterator` and `const char* const*&` different types in the context of template type deduction (in his implementation). Maybe it has to do with the templated type being a pointer and the different places `const` can be applied. For example: `const char **` vs `const char *const *` and such?

In the end, the fix does seem fairly trivial if not terribly elegant. Maybe a compromise would be a local `typedef` to ensure that the code is kept simple?

**Comment by 10110111** [comment] 2015-12-04 20:55
OK, it does make sense. I'm not sure though it'd be enough. We'd better get some feedback from the OP before we do any such changes blindly (i.e. unable to test).

**Comment by 10110111** [comment] 2015-12-04 21:10
BTW, in my `/opt/gcc-5.2/include/c++/5.2.0/array` I have the following declaration in `struct array`:
````
typedef const value_type*			      const_iterator;
````
I.e. `std::array<const char*, 6ul>::const_iterator` should actually be identical to
`const char* const*`. Now I wonder what @FaizSayyid has instead in his
`/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/array`.

**Comment by eteran** [comment] 2015-12-04 21:21
Agreed. Perhaps I can find out which version of Fedora/RHEL/CentOS comes with gcc-4.8.2 and can reproduce in a VM. Without that, like you said, no point in trying to fix blindly.

**Comment by 10110111** [comment] 2015-12-04 21:21
I think I know what happens. After the first change @FaizSayyid got error in exact the same line (increased by one due to addition before it). And the follow-up notes by gcc say that only `std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)` was a candidate function to call. This means that `<algorithm>` header wasn't included at all. And indeed, at least `PlatformState.cpp` doesn't have it up to now. Currently though it is included via `Utils.h` — at least since the time I added `util::contains()` helper.
So I think @FaizSayyid was just unlucky enough to come across a configuration where `<algorithm>` wasn't included by any other header (e.g. Qt), thus if he adds an include of it, the compilation should succeed.

**Comment by eteran** [comment] 2015-12-04 21:26
Interesting. OK, well I think it's probably worth closing this bug for now since @FaizSayyid hasn't followed up and it doesn't seem to be easily reproducible on either our machines or travis CI. If anyone else runs into this issue, we'll know where to start.

**Closed by eteran** 2015-12-04 21:26 UTC
