### ISSUE TITLE
Failed to read 0 bytes from "7eff8f10e100"

### ISSUE THREAD

**Issue by zhqhzj** [eteran/edb-debugger#789] opened 2020-12-16 08:45 UTC
please Report Bugs & Requests At: https://github.com/eteran/edb-debugger/issues
comparing versions: [4864] [4864]
Running Terminal:  "/usr/bin/xterm"
Terminal Args:  ("-title", "edb output", "-hold", "-e", "sh", "-c", "tty > /tmp/edb_temp_file_2026599105_2648;trap \"\" INT QUIT TSTP;exec<&-; exec>&-;while :; do sleep 3600; done")
Terminal process has TTY:  "/dev/pts/2"
Debuggee is now 32 bit
Loading session file
Loading plugin-data
restoreComments
Debuggee is now 64 bit
Failed to read 0 bytes from "7eff8f10e100"
Unable to get signal info for thread 2688 : PTRACE_GETSIGINFO failed: No such process
Saving session file

ENV: VMware Workstation 12 player  +  ubuntu-20-04.1 + edb_1.3.0

**Comment by eteran** [comment] 2020-12-17 02:43
Is this causing you any errors? That check is in there because sometimes some methods of reading don't work. So long as SOME methods work, this it shouldn't be a problem. Can you go into more detail?

**Comment by zhqhzj** [comment] 2020-12-17 06:31
Hi，
















------------------ 原始邮件 ------------------
发件人:                                                                                                                        "eteran/edb-debugger"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 上午10:44
收件人:&nbsp;"eteran/edb-debugger"<edb-debugger@noreply.github.com&gt;;
抄送:&nbsp;"Johnny.zhang"<416642205@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [eteran/edb-debugger] Failed to read 0 bytes from "7eff8f10e100" (#789)





 
Is this causing you any errors? That check is in there because sometimes some methods of reading don't work. So long as SOME methods work, this it shouldn't be a problem. Can you go into more detail?

**Comment by eteran** [comment] 2020-12-17 14:55
@zhqhzj If there was intended to be a message, it was not received. I only see "Hi"

**Comment by eteran** [comment] 2020-12-20 04:02
I am closing this issue due to it not being clear what the issue is. Please reopen if you are able to provide more details.

**Closed by eteran** 2020-12-20 04:02 UTC
