### ISSUE TITLE
EDB doesn't load symbols for its own plugins

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#405] opened 2016-05-05 20:09 UTC
To reproduce:
1. Launch EDB
2. Run EDB as a debuggee
3. Run to main, and further (twice `F9`)
4. `Ctrl+Alt+S`, search for e.g. `PlatformThread`
5. Find nothing, then look into symbols directory and find out that there's even no directory corresponding to `/usr/lib/edb`.

At the same time, GDB is able to locate these libraries and their symbols.

**Comment by eteran** [comment] 2016-05-06 04:00
this likely has to do with when libraries are loaded. I imagine that there are two factors here:

1. edb manually loads plugins, so you'd have to get well into main before they get loaded.
2. there is no "load library' event (but we can in principle create something equivalent), so edb only will only see loaded libs on a stop event after they are loaded.

For me the symbol files definitely get created if I run the sub-process edb to the point where the gui pops up, then stop it.

But I don't see the corresponding symbols in the UI, so there is definitely a bug here.

**Comment by eteran** [comment] 2016-05-06 04:08
Another few things I noticed:

1. there is a good chance that edb will auto-delete some of the symbol files for edb citing that they don't match the binaries. This is because they get invalidated simply by rebuilding edb.
2. It looks like edb may actually be loading the symbols, but some parts of the UI aren't updating immediately. Try following your instructions, but hitting refresh in the symbols dialog after pulling it up. Does it show the symbols then?

**Comment by 10110111** [comment] 2016-05-06 04:37
1. I've actually noticed that the directory and files are created after I stop the inferior. Originally I didn't even stop it, just opened the symbols dialog.
2. Doesn't seem to show even then.

**Comment by AaronOpfer** [comment] 2016-11-24 02:58
> there is no "load library' event (but we can in principle create something equivalent), so edb only will only see loaded libs on a stop event after they are loaded.

It looks like gdb has the ability to detect library loads: [stop-on-solib-events](http://visualgdb.com/gdbreference/commands/set_stop-on-solib-events). I'm curious how that must work.

**Comment by eteran** [comment] 2016-11-27 06:01
@AaronOpfer there is a way to track "library load" events, but it's not simple and it's not perfect.

Basically, the address that the "BinaryInfo::ELFXX::debug_info()" (on unix like systems) resolves to is a "link" structure defined in `link.h`. In there is a pointer to a function which is nothing more than a `ret` instruction and will get called for every library loaded. Place a breakpoint here, and we get what we need!

The only issue really, is that the information is not set fully until ld has finished loading the program (a little bit before main), so if the user opts to not set the initial breakpoint on main, then it will miss some load events until we get a post main breakpoint.

Make sense?

**Comment by 10110111** [comment] 2016-11-27 06:18
Why can't EDB catch these events in an automated way, without dependence on user-set breakpoints?

**Comment by eteran** [comment] 2016-11-27 06:21
It can in general. The trouble is specifically when we have the first opportunity to set the necessary internal breakpoint. The link structure that gives us the location to set it isn't filled out until just before main, so if the user chooses to set the initial breakpoint on the ELF entry point instead of main, we don't get a good opportunity to set the internal BP until we hit a post-main BP (set by the user). 

It's just an ugly corner case :-/

**Comment by eteran** [comment] 2016-12-20 08:09
So we meandered a little off topic. For me, if I follow the step sin the OP, I do in fact see many symbols from the plugins. Do we believe that this bug is still an issue?

**Comment by AaronOpfer** [comment] 2016-12-20 08:11
I guess we need to make a new issue for adding a feature to pause applications on library load.

**Comment by eteran** [comment] 2016-12-20 08:26
@AaronOpfer Good point! #524

**Comment by eteran** [comment] 2016-12-21 21:20
Closing this since I cannot reproduce currently. Feel free to reopen if the problem persists.

**Closed by eteran** 2016-12-21 21:20 UTC
Labels: bug
