### ISSUE TITLE
Cannot load any plugins

### ISSUE THREAD

**Issue by tathanhdinh** [eteran/edb-debugger#546] opened 2017-03-31 15:29 UTC
That seems a stupid issue since nobody has the same problem, but I cannot load any plugins with the lastest version of `edb`. I have checked out the lastest version from the repository, then compile it. There are no problem in compiling, but `edb` reports always `Failed to successfully load the debugger core plugin....`. I have tried to give the correct path to the plugins directory `/usr/local/lib64/edb` (and hopelessly try some other dirs), but it does not work.

**Comment by eteran** [comment] 2017-03-31 22:24
Others have reported a similar issue with loading the core plugin. It seems to be Qt version and build specific. There is a closed bug regarding this. 

What OS and version of Qt are you using (for reproducing purposes)? Is it the stock Qt for your distro? Or is it a 3rd party repo?

Thanks

**Comment by tathanhdinh** [comment] 2017-04-03 10:35
Thanks for the response. I am using `Fedora 25` and `Qt 5.7.1` stocked by this distro.

**Comment by eteran** [comment] 2017-04-23 22:01
I am considering this to be the same issue as #350. So far, I have been unable to reproduce it with Qt 4, I am going to try with Qt5 now too to see if it a Qt 5 specific issue.

**Comment by eteran** [comment] 2017-04-23 22:17
OK, problem on Fedora 25 + Qt 5 has been replicated. I will see if I can fix this ASAP.

**Comment by eteran** [comment] 2017-04-24 04:09
This seems also particularly related to issue #361

**Comment by eteran** [comment] 2017-04-24 16:22
I believe that this is now fixed!

**Closed by eteran** 2017-04-24 16:22 UTC
