### ISSUE TITLE
Could not open

### ISSUE THREAD

**Issue by martin-gametest** [eteran/edb-debugger#332] opened 2016-01-14 09:42 UTC
"Failed to open and attach to process, please check privileges and try again."
edb version: 0.9.20
Linux kali 4.0.0-kali1-amd64 #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) x86_64 GNU/Linux
- login as root!
- client ELF file permision set to 777

Did not work:
$edb #GUI:File-Open
$edb --run client
$sudo edb #GUI:File-Open
$sudo /usr/bin/edb --run /root/client

Also I dont understand why edb looks different beeing run with sudo command?
$edb
![edb](https://cloud.githubusercontent.com/assets/16669304/12320886/72886750-baab-11e5-920d-c702a4b4d676.png)
![edb_about](https://cloud.githubusercontent.com/assets/16669304/12320888/728e24b0-baab-11e5-9313-ae76dc8be263.png)
![edb_about_qt](https://cloud.githubusercontent.com/assets/16669304/12320887/728a0dc6-baab-11e5-9ceb-ee0a7cc0a53a.png)
$sudo edb
![sudo_edb](https://cloud.githubusercontent.com/assets/16669304/12320895/7a53a0a8-baab-11e5-9b83-f62eb9e1e160.png)
![sudo_edb_about](https://cloud.githubusercontent.com/assets/16669304/12320893/7a23b672-baab-11e5-8c5f-eab670969c3d.png)
![sudo_edb_about_qt](https://cloud.githubusercontent.com/assets/16669304/12320894/7a3c5204-baab-11e5-8577-d912a61d9adb.png)

**Comment by eteran** [comment] 2016-01-14 17:54
So to answer why Qt looks different under sudo. It is because it is running as root, which being a different user, is not respecting your user's Qt theme setting.

As for fixing this issue. You seem to be using the 0.9.20 release, can you try to latest from github master? There has been a LOT of changes since the last release, perhaps one of them fixed this?

**Comment by 10110111** [comment] 2016-01-14 18:15
This looks like a duplicate of #329.

**Comment by eteran** [comment] 2016-01-14 18:27
it certainly is, I'll close this one, the conversation was more active in the other.

**Closed by eteran** 2016-01-14 18:27 UTC
