### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by MehmetKursat** [eteran/edb-debugger#738] opened 2019-12-14 15:02 UTC
I've tried to build this on macOS Catalina, but unfortunately I couldn't manage to do it. Is there any macOS port going on actively?

```
-- Checking for module 'double-conversion'
-- Looking for C++ include double-conversion/double-conversion.h
-- Looking for C++ include double-conversion/double-conversion.h - not found
CMake Warning at CMakeLists.txt:61 (message):
  libdouble-conversion header wasn't found.  32- and 64-bit floating-point
  values will be shown with max_digits10 digits of precision instead of
  shortest representation.


CMake Warning at CMakeLists.txt:71 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.


-- Checking for module 'gdtoa-desktop'
--   No package 'gdtoa-desktop' found
CMake Warning at CMakeLists.txt:109 (message):
  gdtoa-desktop package wasn't found.  80-bit floating-point values will be
  shown with max_digits10 digits of precision instead of shortest
  representation.


CMake Error at src/CMakeLists.txt:8 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.0.0) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/Users/-/edb-debugger/build/CMakeFiles/CMakeOutput.log".
See also "/Users/-/edb-debugger/build/CMakeFiles/CMakeError.log".
```

**Comment by eteran** [comment] 2019-12-14 17:01
There currently is no macOS support and it is not expected to build on macOS... **yet**.

The infrastructure is there, but there's a lot of work needed to make it happen as the experimental macOS code I had has not been kept up to date with the internal API changes that have been made over the years.

I'm closing this bug, not because we have no plans for macOS, but because it's technically a duplicate of issue #261

**Closed by eteran** 2019-12-14 17:01 UTC
