### ISSUE TITLE
I follow compiling instructions in wiki for Fedora (mine is 26) and I get an error when executing cmake ..

### ISSUE THREAD

**Issue by q2dg** [eteran/edb-debugger#606] opened 2017-09-24 08:54 UTC
It's this: 

_CMake Error at /usr/lib64/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5XmlPatterns"
  with any of the following names:
    Qt5XmlPatternsConfig.cmake
    qt5xmlpatterns-config.cmake
  Add the installation prefix of "Qt5XmlPatterns" to CMAKE_PREFIX_PATH or set
  "Qt5XmlPatterns_DIR" to a directory containing one of the above files.  If
  "Qt5XmlPatterns" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  src/CMakeLists.txt:27 (find_package)
-- Configuring incomplete, errors occurred!
See also "/home/q2dg/edb-debugger/build/CMakeFiles/CMakeOutput.log"._

I append CMakeOutput.log file for completeness.

[CMakeOutput.log](https://github.com/eteran/edb-debugger/files/1327149/CMakeOutput.log)

I suspect Fedora 26 has something different from Fedora 21 (version which is used in wiki instructions).
Thanks!

**Comment by eteran** [comment] 2017-09-24 16:26
I haven't tried to build it on FC26, it's definitely just a dependency issue. I'll look into it.

**Comment by eteran** [comment] 2017-09-24 16:39
As a note, it looks like you have at least some Qt5 libs installed, so it is defaulting to trying to built against those.

So, it seems that you can either force Qt4 building, or install the following packages:

* qt5-qtbase-devel
* qt5-qtxmlpatterns-devel
* qt5-qtsvg-devel

----

Either way, I am going to update the instructions for FC6 to straight prefer Qt5.

**Comment by eteran** [comment] 2017-09-24 16:41
New instructions confirmed to work on FC26 (via docker image). Closing issue. Please re-open if it persists.

**Closed by eteran** 2017-09-24 16:41 UTC

**Comment by q2dg** [comment] 2017-09-24 22:44
Uau, that's effectiveness and quickness!!
Thanks a lot!!
