### ISSUE TITLE
Negative immediates of 32 bit instructions are shown extended to 64 bits

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#151] opened 2015-07-19 06:37 UTC
Tested on x86 target, the following instructions' immediates are sign-extended to 64 bits, while they shouldn't be:

`89 93 9c 01 ff ff` `lea edx, [ebx+0xffffffffffff019c]` should be `lea edx, [ebx+0xffff019c]`
`ba 83 79 1b 9e` `mov edx, 0xffffffff9e1b7983` should be `mov edx, 0x9e1b7983`.

**Comment by eteran** [comment] 2015-07-19 18:01
Ah, probably a side effect of a recent change. I think I know how to fix it pretty quickly.

Thanks!

**Comment by eteran** [comment] 2015-07-19 18:22
those should be fixed (Although the second example according to all the references I've seen) is supposed to be:

    mov dword ptr [ebx+0x9e1b7983], edx

**Comment by 10110111** [comment] 2015-07-19 19:14
No, the second example is `B8+rd id` in Intel Instruction Set Manual lingo (with `rd=2`, i.e. `edx`), it corresponds to `mov r32, imm32`. GDB will tell you the same.

**Comment by eteran** [comment] 2015-07-19 20:02
Sorry I had them reversed in order in my regression test. The one which appears different is:

    89 93 9c 01 ff ff lea edx, [ebx+0xffffffffffff019c] should be lea edx, [ebx+0xffff019c]

Which seems to be:

    mov dword ptr [ebx+0xffff019c], edx

not an `lea` instruction. Which also agrees with https://www.onlinedisassembler.com/odaweb/WuFlQ9hR/0, I know it's not an authoritative source, but it seems to be correct so far.

Let me know if this is correct, or if you think it still needs correcting.

**Comment by 10110111** [comment] 2015-07-20 03:56
Yes, you're right, it's a `mov`, not `lea`. Intel docs and IDA agree with you.

**Comment by eteran** [comment] 2015-07-20 04:14
wonderful, going to close this issue. Let me know if you find anything else :-)

**Closed by eteran** 2015-07-20 04:14 UTC
Labels: edisassm, Type-Defect
