### ISSUE TITLE
Disassembly view accesses garbage beyond visible region

### ISSUE THREAD

**Issue by 10110111** [eteran/edb-debugger#588] opened 2017-08-12 06:18 UTC
To reproduce, to to the end of current region, and at the address `0x...fe` put bytes `00 90`. You'll get `add [eax+imm32], reg8` instruction, where `imm32` is garbage not actually present in debuggee's address space.

**Comment by 10110111** [comment] 2017-08-12 14:24
It appears to be not a bug, at least the data are not garbage: in my test program, after the region `[0x8048000,0x8049000)` there is another region, `[0x8049000,0x804a000)`, from which the bytes are successfully read by the disassembly view. I'm not sure though that this is good behavior of QDisassemblyView: it makes it look as if there's no bytes after a region, but in reality there's an accessible adjacent region.

**Comment by eteran** [comment] 2017-08-14 03:19
Right, I have noticed this before. I'm not 100% sure what the best policy is to handle this. I can imagine some code which attempts to be unfriendly to debuggers by having some code straddle regions or something to that effect. Maybe we can color the bytes that are from an adjacent region differently so they stand out as "not from here"? I dunno, just throwing out random thoughts.

**Comment by AaronOpfer** [comment] 2017-08-14 03:49
This is probably just a bug somewhere in the disassembly view where we
don't check the bounds before performing a read. I'm guessing that if there
is no adjacent region, we'd show uninitialized memory from the read buffer
instead.

Also, I seem to remember seeing this bug reported before. Did it come back
to life, or did we never fix it?

**Comment by 10110111** [comment] 2017-08-14 06:16
> I'm guessing that if there is no adjacent region, we'd show uninitialized memory from the read buffer
instead.
Not really: I've actually tried to debug it before commenting on this issue. Actual code just relies on being able to read data from the process, and if it succeeds, it doesn't check whether it has just read past the end of the block given to it. The memory is fully initialized, just belongs to a different block of debuggee's address space.

**Comment by eteran** [comment] 2020-12-21 16:57
I think we should declare this as "not a bug" and close this issue. Especially since if limited the display to never display disassembly that crossed region boundaries, a "nefarious" app could decide to place a few instructions on that boundary deliberately in order to make analysis harder. I think that it's best to just allow it for now.

We can always revisit this if it proves to be an issue.

**Closed by eteran** 2020-12-21 16:57 UTC
